packages:
  linux:
    apt:
      # Core packages (always installed)
      core:
        - "curl"
        - "wget"
        - "git"
        - "unzip"
        - "man-db"
        - "eza"
        # - "tree"
        - "openssh-client"
        - "fontconfig"
        - "zsh"

      core+:
        - "file" # yazi dependencie: for file type detection
        - "7zip" # yazi dependencie: for archive extraction and preview
        - "jq" # yazi dependencie: for JSON preview
        - "poppler-utils" # yazi dependencie: for PDF preview
        - "fd-find" # yazi dependencie: for file searching
        - "ripgrep" # yazi dependencie: for file content searching
        - "fzf" # yazi dependencie: for quick file subtree navigation
        - "zoxide" # yazi dependencie: for historical directories navigation
        # - 'ffmpeg' # yazi dependencie: for video thumbnails
        # - "resvg" # yazi dependencie: for SVG preview
        - "xclip" # yazi dependencie: for Linux clipboard support
        - "wl-clipboard" # yazi dependencie: for Linux clipboard support
        - "xsel" # yazi dependencie: for Linux clipboard support
        - "bat"
