packages:
  linux:
    apt:
      # Core packages (always installed)
      core:
        - "curl"
        - "wget"
        - "git"
        - "unzip"
        - "man-db"
        - "eza"
        - "jq" # yazi dependencie
        # - "tree"
        - "openssh-client"
        - "fontconfig"
        - "zsh"
        - "file" # yazi dependencie
        # - 'ffmpeg'
        - "7zip" # yazi dependencie
        - "poppler-utils" # yazi dependencie
        - "fd-find" # yazi dependencie
        - "ripgrep" # yazi dependencie
        - "fzf" # yazi dependencie
        - "zoxide" # yazi dependencie
        - "xclip" # yazi dependencie
        - "wl-clipboard" # yazi dependencie
        - "xsel" # yazi dependencie
      core+:
        - "bat"
