packages:
  linux:
    apt:
      # Core packages (always installed)
      core:
        - "curl"
        - "wget"
        - "git"
        - "unzip"
        - "man-db"
        - "eza"
        - "tree"
        - "openssh-client"
        - "fontconfig"
        - "zsh"

      core+:
        # - "yazi" # No apt package, traited by .chezmoiexternal
        - "file" # yazi dependencie: for file type detection
        - "7zip" # yazi dependencie: for archive extraction and preview
        - "jq" # yazi dependencie: for JSON preview
        - "poppler-utils" # yazi dependencie: for PDF preview
        - "fd-find" # yazi dependencie: for file searching
        - "ripgrep" # yazi dependencie: for file content searching
        - "fzf" # yazi dependencie: for quick file subtree navigation
        - "zoxide" # yazi dependencie: for historical directories navigation
        # - 'ffmpeg' # yazi dependencie: for video thumbnails
        # - "resvg" # yazi dependencie: for SVG preview
        - "xclip" # yazi dependencie: for Linux clipboard support
        - "wl-clipboard" # yazi dependencie: for Linux clipboard support
        - "xsel" # yazi dependencie: for Linux clipboard support
        - "bat"

  windows:
    winget:
      core:
        - "twpayne.chezmoi"
        - "Git.Git"
        - "Microsoft.PowerShell"
        - "Microsoft.VisualStudioCode"
        - "JernejSimoncic.Wget"
        - "JanDeDobbeleer.OhMyPosh"
        # - "Terminal-Icons"
        - "eza-community.eza"
        - "Fastfetch-cli.Fastfetch"

      core+:
        - "sxyazi.yazi" # Terminal File Manager
        - "7zip.7zip" # yazi dependencie: for archive extraction and preview
        - "jqlang.jq" # yazi dependencie: for JSON preview
        - "oschwartz10612.Poppler" # yazi dependencie: for PDF preview
        - "sharkdp.fd" # yazi dependencie: for file searching
        - "BurntSushi.ripgrep.MSVC" # yazi dependencie: for file content searching
        - "junegunn.fzf" # yazi dependencie: for quick file subtree navigation
        - "ajeetdsouza.zoxide" # yazi dependencie: for historical directories navigation
        # - "ImageMagick.ImageMagick" # yazi dependencie: for image preview
        # - "Gyan.FFmpeg" # yazi dependencie: for video thumbnails

    powershellModule:
      core:
        - "NerdFonts"
