packages:
  linux:
    # Core packages (always installed)
    core:
      apt:
      - 'curl'
      - 'wget'
      - 'git'
      - 'unzip'
      - 'man-db'
      - 'eza'
      - 'jq'
      - 'tree'
      - 'openssh-client'
      - 'fontconfig'
      - 'zsh'
      - 'ffmpeg'
      - '7zip'
      - 'poppler-utils'
      - 'fd-find'
      - 'ripgrep'
      - 'fzf'
      - 'zoxide'
      - 'xclip'
      - 'wl-clipboard'
      - 'xsel'